### ISSUE TITLE
jodconverter has moved to a public organization

### ISSUE THREAD

**Issue by sbraconnier** [jodconverter/docker-image-jodconverter-examples#27]
Hello there. I couldn't find how to contact you so here it is.

I moved JODConverter to an organization repo:
https://github.com/jodconverter/jodconverter

You will have to update your repo to reflect that. 

You probably received an invitation. You are a full maintainer of the new jodconverter repository. You can commit everything you want without my permission, I trust you completely.

I would like to have a way to contact you in order to share my vision about the project. Maybe start a discussion in the jodconverter organization?

**Comment by EugenMayer** [comment]
@sbraconnier sorry, i blocked all the direct comms on github due to the mass of exploit comms i got via the platform.

Thank you for the trust. I am super happy to lend a helping hand as far as i can be useful. Actually we might start to move this project over in the organization, if you like. This project basically has the only purpose of providing an runtime environment for jodconverter, including some out of the box test projects like the REST plugin. 

So all it does is re-packing jodconverter, thus would fit the family. What do you think.

I'am not abel to contact you via github either AFAICS, so sharing my contact is oddly hard :)

**Comment by sbraconnier** [comment]
Sorry for the delay.... We have power failures here in canada (est) caused by an enormous storm raging since 2 days now...

I had to publish my personal email in order to be able to make the project accessible through [maven](https://mvnrepository.com/artifact/org.jodconverter/jodconverter-local/4.4.5) (developers section). So no big deal publishing it here. It's my full name at gmail (simonbraconnier@gmail.com).

I would really like if you could move this beautiful project in the jodconverter organization. But would like to share my short term vision first to be sure you don't spent time on this and then I do something that will break your work.

The next thing I'll do will be to move the "samples" module from the jodconverter repository in order to have a separated ''samples" project (repository) we could work on that could grow over time. It would also simplify the build of the main project which must exclude those project from the publishing task, code covering task, etc.

I guess that would probably affect your project since it depends on the REST sample project, right?

I'll probably do this after the christmas holidays, so early january.

Enjoy your holidays and merry christmas!! :)

**Comment by EugenMayer** [comment]
@sbraconnier sorry all the free days took some time :)

I really like you idea, also the idea of splitting out the example repository into it's own project. 

I would say we have 2 different efforts, i would like to define how we go about them:

## move example projects into own projects

Do you have experience in composite builds with gradle and are you aware how to go about this? Just would not like you to be surprised by that - if you are aware about this impact and the changes, just ignore this comment.

The pros are, the main project can move under more strict rules, not getting forced to be released due to 'spring boot upgrades in the example projects' - the example project can have more contributions since it is light weight and the impact can be somewhat limited. So i guess "robustness" is the key here (less expected side effects by accident) and less releases for version bumps.

On the other side, the composite builds will be something to deal with. For my experience, this complication is easy to deal with locally when the developers do have a convention how to name the repos and where to put them relatively. Thus we can have a snippet that can be uncommented to activate the composite build temporary, this snippet should never be checked in. I assume you might have experience with that - local composite builds are easy as long as the folder-structure of the repos can be defined in a convention.

The harder problem is CI and thus running the test against a "not yet released version". So assume the example should be tested against branch/pr-X of jodconverter. This can be done locally, but running this in the CI is way harder. Usually this would mean that every PR build on jodconverter is published as a snapshot build with a namespaced release, like 0.0.0-branchname-SNAPSHOT - so one could reference it in the example project.

## move this docker-image-building-repo into the organization

Since this repo does include 2 aspects: 
a) Building an runtime environment for the jodconverter (lets call it base image) - so libreoffice with patches, fonts or whatever
b) using the base image, build the example projects (REST with GUI)

I wonder if we should split those projects into 2 repos. The base image and the example projects - and move the latter to the new example project repo you plan.

Sorry for the lengthy comment - but i guess when we want to restructure, some planning ahead will help avoiding pitfalls.

**Comment by EugenMayer** [comment]
@sbraconnier i was bold and actually did my part. I moved this repo into organization and moved out the "base image" (aka runtime) part into  the project https://github.com/jodconverter/docker-image-jodconverter-runtime.

This project only builds the examples (and using the runtime as the base image) (yet cloning the example project).

I publish the images to `jodconverter/jodconverter-runtime` and `jodconverter/jodconverter-examples`

I also adjusted the READMES (and most probably missed things), so be sure to review those
 - https://github.com/jodconverter/docker-image-jodconverter
 - https://github.com/jodconverter/docker-image-jodconverter-runtime

@sbraconnier could you somehow give me the "admin" permissions on this repository? I kind of lost those and cannot access the settings. I would like to rename the repository in something like `jodconverter-examples` or for now `docker-image-jodconverter-examples`

**Comment by sbraconnier** [comment]
Wow nice work. I'm on my phone ATM with limited internet access. I look forward to have time to take a closer look to all the work you have done the last few days.

@EugenMayer You should be admin now.

**Comment by EugenMayer** [comment]
Thank you - do no worry. Let me know what you are around at your desk!

**Comment by EugenMayer** [comment]
@sbraconnier could you please allow making packages publin in the organziation:

![image](https://user-images.githubusercontent.com/136934/210170301-addcad10-08eb-467f-a2b8-b500849abbd2.png)

Otherwise other poeple cannot download jodconverter-runtime / jodconverter-examples

**Comment by EugenMayer** [comment]
@sbraconnier i'am kind of blocked by this, could you adjust the settings or give me the according permissions to do so? Thank you

**Comment by sbraconnier** [comment]
Sorry! Didn't see that last request! I'm still on my phone with limited internet acces until January 9. I'll do it right away...

**Comment by sbraconnier** [comment]
@EugenMayer You should be able to do it now..

**Comment by EugenMayer** [comment]
@sbraconnier thank you. I finished moving the repos, docs and builds to the new org and as far as i can see, it is working now .So i assume the first step is done and i hope it is an improvement.

I guess there is the open point / effort if the example project code should be split out from the actual main project - maybe you could comment on https://github.com/jodconverter/docker-image-jodconverter-examples/issues/27#issuecomment-1367808223 at some point so we could start a discussion if you like

**Comment by EugenMayer** [comment]
@sbraconnier should we plan a release with spring boto 3.0 compatibility and maybe also anouncing the "new" (relocated) example projects (docker images only yet)? I think having the sb 3.0 compat is a value that is worth an release.

**Comment by sbraconnier** [comment]
I totally agree with you! It's been a crazy come back to work for me after the holidays. It should calm down a little this week and I hope I'll be able to release a version in order to be compatible with the latest version of spring boot. Then, we could decide what's the next step. I have a couple emails to anwsered to in my inbox regarding jodconverter too. I won't watch a lot of Nextflix next week :).

**Comment by sbraconnier** [comment]
@EugenMayer Regarding [#17 (comment)](https://github.com/jodconverter/docker-image-jodconverter-examples/issues/27#issuecomment-1367808223), I was thinking more of something completely separated from the main project, like the Gradle team did in their organization (see the [kotlin-dsl-samples](https://github.com/gradle/kotlin-dsl-samples) or [gradle-enterprise-build-config-samples](https://github.com/gradle/gradle-enterprise-build-config-samples) for examples). It's only when a version would be released that we would have to update the sample projects (when we have time to do so... as you can see, the Gradle team are a couple versions behind for the kotlin samples, but they are still valid for people looking for kotlin examples, while their enterprise config samples are up to date). We could open an issue for each release to help us remembering to update them. Something simple...

I'm not familiar with composite build, so I can't comment much about it at the moment, but I would really like for people to clone the samples repo only and be able to run the samples without cloning the main project. Is that possible with composite build ? I don't think so from what I read so far.

What do you think ?

**Comment by EugenMayer** [comment]
I'am with you that the defautl repo configuration of the example repo should be from release. We could even  use some version constraints  like 1.2.+, so we could even auto-upgrade them on the patch version without touching the repository at all.

Composite builds are for us rather then for the usual person that checks out the the example repo.
The example repo is configured to use one of the releases,
When we checkout the repo, we can activate the composite build and the jodconverter repo is next to it, so one can develop both at a time (if needed at all).

But yes, not a huge deal, if you want to decouple the example development from the main repo and only touch them if needed. 

Let me undestand, will the spring-boot-starter project still stay in the main repository?

**Comment by sbraconnier** [comment]
I understand the idea better now.

As for the `jodconverter-spring` and `jodconverter-spring-boot-starter` projects, yes I would let them as part of the main project, since they will be released at the same time, and published into the maven central repository.

I would only move the` jodconverter-samples` module, and all the sample projects it contains. It would allow us to simplify the gradle configuration since those projects are not published (must be excluded from the publication task).

**Comment by EugenMayer** [comment]
All for it, sounds good and sound!

**Comment by sbraconnier** [comment]
It's done. I've probably broken your project!! I'll update the `jodconverter-samples` repo once the release 4.4.6 will be available from the maven central.

Feel free to do it youself if you see it before me. I'm done for the day :)

**Comment by EugenMayer** [comment]
@sbraconnier should we close this issue. I assume we have done what we planned here and it's there and alive. What is your take on this?

**Comment by sbraconnier** [comment]
Indeed! Feel free to close it! :)
